---
- name: "PLAYBOOK TO CONFIGURE OSPF"
  hosts: all
  connection: ansible.netcommon.network_cli
  gather_facts: no
  
  tasks:

    - name: "CONFIGURE INTERFACE DESCRIPTION"
      cisco.nxos.nxos_interfaces:
        config:
          - name: "{{ item.name }}"
            description: "Configured by Ansible"
            enabled: true
      loop: "{{ interfaces }}"

    - name: "CONFIGURE IP ADDRESS ON INTERFACES"
      cisco.nxos.nxos_l3_interfaces:
        config:
          - name: "{{ item.name }}"
            ipv4:
              - address: "{{ item.ip_address }}"
      loop: "{{ interfaces }}"
    
    - name: "ENABLE OSPF FEATURE"
      cisco.nxos.nxos_feature:
        feature: ospf
        state: enabled

    - name: "CONFIGURE OSPF PROCESS"
      cisco.nxos.nxos_ospfv2:
        config:
          processes:
            - process_id: "{{ ospf.process_id }}"
              router_id: "{{ interfaces | map(attribute='ip_address') | first | ansible.netcommon.ipaddr('address') }}"

    - name: "CONFIGURE OSPF ON INTERFACES"
      cisco.nxos.nxos_ospf_interfaces:
        config:
          - name: "{{ item.name }}"
            address_family:
              - afi: "ipv4"
                processes:
                  - process_id: "{{ ospf.process_id }}"
                    area:
                      area_id: "0.0.0.0"
                      secondaries: no
      loop: "{{ interfaces }}"
      when: item.ospf == 'enabled'
