---
- name: "PLAYBOOK TO RETRIEVE THE RUNNING CONFIGURATION"
  hosts: all
  connection: ansible.netcommon.network_cli

  tasks:
  
    - name: "SAVE RUNNING CONFIG TO DIRECTORY PATH" 
      cisco.nxos.nxos_config: 
        backup: yes
        backup_options:
          dir_path: <directory-path>
