---
- name: ENSURE TENANT CONFIGURATION EXISTS
  hosts: apic
  connection: local
  gather_facts: False
  
  vars_prompt:
    - name: "tenant"
      prompt: "Please enter the desired name of your Tenant: "
      private: no

  tasks:
    - name: ENSURE TENANT EXISTS
      aci_tenant:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ tenant }}"
        description: "Tenant Created Using Ansible"
